### ISSUE TITLE
vendor update.zip

### ISSUE THREAD

**Issue by Ryogo-X** [limerainne/ridi_paper_pro_ntx_6sl_twrp#1]
Hello.

Have not found better way to contact you.
First thing first - can you please correct spelling of my nickname in readme? :)
And second - could you, by any chance, share firmware (like vendor update.zip or boot + system backups from TWRP) for Paper Pro?

**Comment by limerainne** [comment]
Oh... sorry for misspelling your nickname... I fixed readme file.

Also, because I'm not related to Ridibooks company, that company did not post system update package publicly, and I can't confident that there could not be any copyright issue from sharing system image, hence I'm sorry I can't help you for now.

**Comment by Ryogo-X** [comment]
@limerainne ok, thanks anyway :)
